### ISSUE TITLE
USB - ISS with Adafruit I2C devices

### ISSUE THREAD

**Issue by corteXnzt** [sneakypete81/usb_iss#101]
* usb_iss version: 7
* Python version: 2.7.15+
* Operating System: Ubuntu 18.04

### Description

USB - ISS i2c mode shows false when I call iss.i2c.test(add). 

### What I Did
This happens when i2c devices from adafruit is connected. 
The adafruit i2c devices are working if via arduino. When I connect SRF10 from the same USB ISS manufacturer it shows True. So i'm not sure what is wrong. Tried also removing the on board pull ups on the adafruit devices but same output with .test command which shows false.

with SRF10
```
Mode.I2C_H_100KHZ
True
```
with HTU21DF and DRV2605
```
Mode.I2C_H_100KHZ
False
```

**Comment by sneakypete81** [comment]
Is the voltage jumper on the USB ISS board set correctly for the adafruit device?

If you have access to an oscilloscope you could check that the signalling looks correct.

**Comment by corteXnzt** [comment]
Thank you for fast response. The voltage is set to 5v since SRF10 uses 5v and the adafruit devices are compatible with either 3.3v or 5v.  Arduino clock rate default is set to 100kHz. I don't have access to that device right now, someone borrowed it. I could try tomorrow if it is returned to me.

**Comment by sneakypete81** [comment]
I'm happy to look at the Python setup code you're using, otherwise I think you'll need to take this up with the USB ISS board suppliers (https://robot-electronics.co.uk/).

**Comment by corteXnzt** [comment]
I just used this to see if I can receive a reply.

```

from usb_iss import UsbIss, defs

# Configure I2C mode

iss = UsbIss()
iss.open("/dev/ttyACM0")
data = iss.read_fw_version()
print(data)
iss.setup_i2c(100)
data = iss.read_iss_mode()
print(data)

#iss.i2c.write(0x5A,0x01,[0])
data = iss.i2c.test(0x5A)
#data = iss.i2c.read(0x5A,0x00,1)

print(data)

```

And btw I have this and got the haptic feedback working with this one. But this USB ISS has smaller form factor and with the ft232 I still need to port the ultrasonic code again.
https://www.elecrow.com/cjmcu-ft232h-high-speed-multifunctional-usb-to-jtag-uart-fifo-spi-i2c-module-for-arduino.html

**Comment by sneakypete81** [comment]
It might be an addressing problem. The I2C methods take an 8-bit device address and set/clear the LSB to signal read/write. Your address (0x5A) is perhaps a 7-bit address, so needs shifting left by one bit (0xB4).

Could you check this, please?

Sorry for the confusion here. I think this needs clearer documentation, and it's probably also worth changing to 7-bit addressing in the API and doing the bit shift in the usb_iss library, since that seems to be the more common usage (including adafruit).

**Comment by corteXnzt** [comment]
You are definitely right cause when I use the SRF10 with the FT232H the default address 0xE0 is not accessible instead it is on 0x70.  

It's fine, no worries. It is my first time using 8 bit device address that I assumed all of this modules always use 7-bit. 

We are on a long weekend in our country due to all saints day. I'll do the test on Monday when I get back to the office. 

Thank you again for support!

**Comment by corteXnzt** [comment]
Hello, confirming this. Just tested Adafruit HTU21D-F with address 0x40 and with shifted one bit left 0x20, shows true / accessible. Thank you again! Closing this issue.

**Comment by sneakypete81** [comment]
Thanks @corteXnzt.

I'm going to change the API to 7-bit addressing for the next release (v2.0.0). This will break existing code unfortunately, but will hopefully prevent this for people in future.
