### ISSUE TITLE
[DOC]: I2C addres in i2c direct method

### ISSUE THREAD

**Issue by rqx110** [sneakypete81/usb_iss#236]
the usage of  `i2c.direct` from the [doc](https://usb-iss.readthedocs.io/en/v2.0.1/usb_iss.html#usb_iss.i2c.I2C.direct):
```py
# Equivalent to iss.i2c.write_single(0x40, 0x55)
iss.i2c.direct([
    defs.I2CDirect.START,
    defs.I2CDirect.WRITE2,
    0x40,
    0x55,
    defs.I2CDirect.STOP,
]);
```
here the `0x40` in `write_single` method is a 7bit-address. however in `direct`  it should be a 8bit-address: `0x80` (0x40 << 1) .
Am I right?

**Comment by sneakypete81** [comment]
You're right :-). Thanks for raising this.
