### ISSUE TITLE
Combining efforts

### ISSUE THREAD

**Issue by DancingQuanta** [sneakypete81/usb_iss#7]
Hi I am author of [pyusbiss](https://pypi.org/project/pyusbiss/) and while looking at how people has been uding my library I discovered this project.

I want to start a conversation so I can understand your vision for this project and thoughts about combining our projects.

I have created my own project some years ago to use SPI protocol of USB-ISS and designed my library in a such a way to looks like `spidev` so that I can use other applications designed for `spidev` without modifying them.
However, I have not have a chance to develop my project further to use other modes because I have a little use for them.

You clearly have done much more work to make rest of USB-ISS accessible via Python.
My thoughts is then I could contribute my SPI code to your project to give it more SPI functionality. Your SPI functionality is limited to `transfer` while mine have `mode` for controlling SPI modes etc.

**Comment by sneakypete81** [comment]
Thanks very much for your message, I'm always very happy to look at PRs.

This module should already handle SPI mode setting though - see https://usb-iss.readthedocs.io/en/latest/usb_iss.html#usb_iss.UsbIss.setup_spi.

For example:
```python
    from usb_iss import UsbIss, defs

    iss = UsbIss()
    iss.open("COM3")

    iss.setup_spi(defs.SPIMode.TX_ACTIVE_TO_IDLE_IDLE_LOW, clock_khz=500)

    data = iss.spi.transfer([0, 1, 2]);
```

Providing a spidev-compatible interface might be a useful extension though, perhaps by adding a new  `spidev` attribute to the `UsbIss()` class.

**Comment by sneakypete81** [comment]
On second thoughts, perhaps it would be better to keep a separate `SpiDev()` top-level class that calls `UsbIss()` methods.

**Comment by sneakypete81** [comment]
Closing for now - I don't personally have a use for a spidev compatibility layer, but would be happy to review a PR.
