### ISSUE TITLE
Test Code Quality

### ISSUE THREAD

**Issue by RechardSG** [sneakypete81/usb_iss#76]
* usb_iss version:0.3.1
* Python version:3.6.5
* Operating System:Windows 10

### Description

Hi Pete, thank you so much for the amazing usb_iss project, it saves me tons of time establishing communication to my SPI slave chips. 
If you don't mind, I have a (very general) question regarding the unittest code (and probably any other code), would you mind sharing with me what is important to you in terms of code quality?
I am trying to use Pylint to assess the quality in terms of docstring, error detection etc.

Thank you!
Rechard

**Comment by sneakypete81** [comment]
Thanks Rechard, I'm really pleased that you find this library useful.

I've used flake8 for linting. If pylint indicates a significant code quality issue then I'd be very happy to review a PR - probably best to start with something small to show the kind of thing that you have in mind. I'd be wary of introducing API changes unless there's a reasonable benefit.

In general, my view is that unit test code should be clear enough not to require comments, unless the intent needs describing. The external API should be described very clearly and precisely. Internal interfaces fall somewhere in between, but favouring clean, clear code over documentation.

I hope that helps, I'm not sure how well I've met these goals, but that's the idea :-).

**Comment by RechardSG** [comment]
> Thanks Rechard, I'm really pleased that you find this library useful.
> 
> I've used flake8 for linting. If pylint indicates a significant code quality issue then I'd be very happy to review a PR - probably best to start with something small to show the kind of thing that you have in mind. I'd be wary of introducing API changes unless there's a reasonable benefit.
> 
> In general, my view is that unit test code should be clear enough not to require comments, unless the intent needs describing. The external API should be described very clearly and precisely. Internal interfaces fall somewhere in between, but favouring clean, clear code over documentation.
> 
> I hope that helps, I'm not sure how well I've met these goals, but that's the idea :-).

Thanks a lot Pete! Honestly I am new to unit test and to code quality assessment too so your advice above would greatly benefit me in both topics. I will read more starting from here and hopefully apply them into my code more. Regarding the API provided so far they have worked greatly for me. Once again thank you!
