### ISSUE TITLE
Maintain IOType when using setup_i2c or setup_serial

### ISSUE THREAD

**Issue by SamP20** [sneakypete81/usb_iss#96]
`setup_i2c` and `setup_serial` currently overwrite the IOType, even if you don't specify any arguments. It would be nice for `UsbIss` to keep track of the previously assigned state and use that if no `ioX_type`arguments are provided.

As an example:

1. `iss.setup_io(io1_type=IOType.OUTPUT_HIGH)`
2. `iss.setup_i2c(100)` <- This currently changes `io1_type` to `IOType.DIGITAL_INPUT`

I'd be happy to create a PR if this is a feature you'd be interested in.

**Comment by sneakypete81** [comment]
Sounds good to me, thanks! PRs gratefully received.

I'd suggest doing this for all of the setup methods to change the default `io*_type` parameter from DIGITAL_INPUT to None.

This is a breaking API change, so would need communicating carefully.

I'm glad you're finding this library useful!

**Comment by sneakypete81** [comment]
Released as v1.0.0. Thanks again for doing this.
